config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'songs#top'
resources :artists, shallow: true do
resources :songs do
resources :post_poems do
resources :post_trans
			end
		end
	end
end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :songs, dependent: :destroy

	validates :artist_name, presence: true, uniqueness: true, length: { in: 2..20 }


end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


    def index
    	@artists = Artist.all.order(created_at: :desc)
        @search_a = Artist.ransack(params[:q])
        @search_artists = @search_a.result.page(params[:page])
    end

    def new
        @artist = Artist.new
        @song = @artist.songs.build
        @poem = @song.post_poems.build
    end

    def create


    	@artist = Artist.new(artist_params)
    	if @artist.save
    	redirect_to new_artist_song_path(@artist), notice: "アーティスト作成に成功しました。"
    	else
    	render :new, notice: "アーティストの作成に失敗しました。"
    	end


    end




    def show
        @artist = Artist.find(params[:id])
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def update
        @artist = Atist.find(params[:id])
        @artist.user_id = current_user.id
        if @artist.update(artist_params)
            redirect_to artist_path(@artist.id), notice: 'アーティスト名が編集されました。'
        else
            render :index, notice: 'アーティストの編集に失敗。'
        end
    end

    def destroy
        artist = Artist.find(params[:id])
        if artist.delete
        redirect_to artists_path, notice: 'アーティストは削除されました。'
        else
            render :index, notice: 'アーティストの削除に失敗。'
        end
    end

    private
    def artist_params
        params.require(:artist).permit(:artist_name,
                                        songs_attributes: [:id, :artist_id, :album_name, :song_name, :_destroy,
                                        post_poems_attributes: [:id, :song_id, :poem, :_destroy,
                                            post_trans_attributes: [:id, :post_poem_id, :song_translate]]])
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
	<ul class="msr_flow02">
	  <li class="active">Artists</li>

	  <%= search_form_for @search_a do |f| %>
		 <div class="form-row ml-5 mb-3">
		 	<div class="col-md-3 offset-md-4">
		<!-- 　　#検索対象のカラムを:hoge_contで示す。itemnameだったらitemname_cont -->
		   <%= f.search_field :artist_name_cont, placeholder:"アーティスト名", class: "form-control" %>
			</div>
		 <%= f.submit "Search", class: "btn btn-sm btn-outline-dark btn-base-1 mt-20" %>
		 </div>
		<% end %>

	</ul>

<div class="main-visual">
</div>






<!-- テーブル -->
<div class="table-2">
			<table class="table">
					<thead>
						<tr>
							<th class="text-center">Artist</th>
<!-- 							<th></th>
							<th></th>
							<th></th>
							<th></th>
 -->						</tr>
					</thead>

					<tbody>

						<% if @search_artists.any? %>
						 <% @search_artists.each do |result| %>



									<tr class="border-bottom">
			<!-- 							<td></td> -->

										<td class="text-center">
											<%= link_to artist_songs_path(result.id) do %>

										   <h6><%= result.artist_name %></h6>

										   <% end %>
										</td>

			<!-- 							<td></td>
										<td></td>
										<td></td> -->

									</tr>
						 <% end %>
						<% end %>

					</tbody>
			</table>
</div>
<!-- テーブル -->


<!-- %h2= page_entries_info @data
= paginate @data -->
<h4>
	<%= page_entries_info @search_artists %>
</h4>

<%= paginate @search_artists, class: "paginate" %>

app/views/artists/new.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">アーティスト登録</li>
  </ol>
</nav>

                <%= form_for(@artist) do |f| %>
                    <% if @artist.errors.any? %>
                      <div id="error_explanation">
                        <h3><%= pluralize(@artist.errors.count, "error") %> invalidated your post.</h3>
                        <ul>
                        <% @artist.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group has-icon">
                        <h5>アーティスト名</h5>
                          <%= f.text_field :artist_name, size: "36" %>
                        </div>
                      </div>
                    </div>
<!--                     <div class="row">
                      <div class="col-md-12">
                        <h5>曲名</h5>
                        <%#= f.text_area :body, size: "35x2" %>
                      </div>
                    </div> -->
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.submit "create artist", class: "btn btn-lg btn-primary btn-base-1 mt-20" %>
                      </div>
                    </div>
                <% end %>