config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'songs#top'
resources :artists, shallow: true do
resources :songs do
resources :post_poems do
resources :post_trans
			end
		end
	end
end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :artist, optional: true


	has_many :post_poems, inverse_of: :song
	accepts_nested_attributes_for :post_poems, reject_if: :all_blank, allow_destroy: true
	has_many :post_trans, through: :post_poem, dependent: :destroy


	has_many :favorites, dependent: :destroy


	validates :album_name, length: { maximum: 60 }

	validates :song_name, presence: true, length: { maximum: 30 }

	validates :artist_id, :uniqueness => {:scope => :song_name}

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def top
        @songs = Song.all.order(created_at: :desc)
    end

    def index
        @artist = Artist.find(params[:artist_id])
    	@songs = Song.all.order(created_at: :desc)
        @search_s = Song.ransack(params[:q])
        @search_songs = @search_s.result.page(params[:page])
    end

 	def new
 		@song = Song.new
        @poem = @song.post_poems.build

    end

    def create
    	@song = Song.new(song_params)
        if@song.save!
    	redirect_to song_path(@song), notice: "曲の作成に成功しました。"
    	else
        @song.post_poems.build
    	render :new, notice: "曲の作成に失敗しました。"
    	end

    end


    def show
    	@song = Song.find(params[:id])
        @poem = @song.post_poems
    end

    def edit
    	@song = Song.find(params[:id])
    end

    def update
    	@song = Song.find(params[:id])
    	if @song.update(song_params)
			redirect_to song_path(@song.id), notice: '曲名が編集されました。'
    	else
			render :index, notice: '曲の編集に失敗。'
    	end
    end

    def destroy
    	song = Song.find(params[:id])
    	if song.delete
    	redirect_to songs_path, notice: '曲は削除されました。'
    	else
    		render :index, notice: '曲の削除に失敗。'
    	end
    end

    private
    def song_params
    	params.require(:song).permit(:artist_id, :song_name, :album_name,
            post_poems_attributes: [:id, :poem, :song_id, :_destroy,
                post_trans_attributes: [:id, :post_poem_id, :_destroy, ]])
    end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_post_poem_fields.html.erb
 <div class="nested-fields well well-compact">
  <div class="form-group">
    <%= f.label :poem, "センテンス" %>
    <%= f.text_area :poem %><br>
    <%= link_to_remove_association "remove poem", f %>
  </div>
</div>

app/views/songs/index.html.erb
	<ul class="msr_flow02">
	  <li><%= link_to "Artists", artists_path, class: "text-color-white" %></li>
	  <li class="active">Songs</li>
	  <%= search_form_for @search_s,:url => {:action => :index} do |f| %>
		  <div class="form-row ml-5 mb-3">
		 	<div class="col-md-3 offset-md-4">
		<!-- 　　#検索対象のカラムを:hoge_contで示す。itemnameだったらitemname_cont -->
		   <%= f.search_field :song_name_cont, placeholder:"曲名", class: "form-control" %>
		 	</div>
		 <%= f.submit "Search", class: "btn btn-sm btn-outline-dark btn-base-1 mt-20" %>
		  </div>
		<% end %>
	</ul>






<div class="main-visual">
</div>






<!-- テーブル -->
<div class="table-2">
			<table class="table">
					<thead>
						<tr>
							<!-- <th></th> -->
							<th class="text-center">Song Title</th>
<!-- 							<th></th>
							<th></th>
							<th></th>
							<th></th> -->
						</tr>
					</thead>

					<tbody>

					<% if @search_songs.any? %>
						<% @search_songs.each do |result| %>


							<tr class="border-bottom">


							   	<td class="text-center">
								<%= link_to song_path(result.id) do %>
								<h6><%= result.song_name %></h6>
								<% end %>
							   	</td>

							</tr>


						<% end %>
					<% end %>
					</tbody>
			</table>
</div>
<!-- テーブル -->












<!-- %h2= page_entries_info @data
= paginate @data -->
<h4>

	<%= page_entries_info @search_songs %>
</h4>
<%= paginate @search_songs, class: "paginate" %>

app/views/songs/new.html.erb
<nav aria-label="パンくずリスト">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a><%= link_to "アーティスト登録", new_artist_path %></a></li>
    <li class="breadcrumb-item active" aria-current="page">曲の登録</li>
  </ol>
</nav>

                <%= form_for [@artist, @song], :url => {:action => :create} do |f| %>
                    <% if @song.errors.any? %>
                      <div id="error_explanation">
                        <h3><%= pluralize(@song.errors.count, "error") %> invalidated your post.</h3>
                        <ul>
                        <% @song.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group has-icon">
                        <h5>曲名</h5>
                          <%= f.text_field :song_name, size: "36" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <h5>アルバム名</h5>
                        <%= f.text_field :album_name, size: "35x2" %>
                      </div>
                    </div>

                    <!-- poem -->
                    <%= f.fields_for :post_poems do |poem| %>
                        <%= poem.label :センテンス %>
                        <br>
                        <%= poem.text_field :poem, size: "70x2" %>
                    <% end %>

                    <div class="links">
                      <%= link_to_add_association "タグを追加", f, :post_poems %>
                    </div>
                    <!-- ポエム -->

                    <div class="row">
                      <div class="col-md-12 actions">
                        <%= f.submit "create song", class: "btn btn-lg btn-primary btn-base-1 mt-20" %>
                      </div>
                    </div>
                <% end %>

app/views/songs/show.html.erb
<h1>曲名</h1>
<br>
<%= @song.song_name %>
<br>
<br>
<h2>アルバム名</h2>
<%= @song.album_name %>
<br>
<br>
<h3>歌詞</h3>

<% @song.post_poems.each do |poem| %>

<br>

	<% if user_signed_in? %>

		<%= link_to post_poem_path(@song.id) do %>
			<%= poem.poem %>
		<% end %>

	<% else %>

		<%= poem.poem %>

	<% end %>

<br>

<% end %>

app/views/songs/top.html.erb
<div class="main-visual">
</div>
				<table class="table">
					<thead class="text-center">
						<tr>
							<th class="text-center">Latest Posts</th>
						</tr>
					</thead>
					<tbody class="text-center">
						<% if @songs.present? %>
							<% @songs.each do |song| %>
								<tr>
									<td class="border-bottom "><%= link_to song_path(song.id), class: "song_#{song.id}" do %>
										<%= song.song_name %>
										<% end %>
									</td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>