config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'songs#top'
resources :artists, shallow: true do
resources :songs do
resources :post_poems do
resources :post_trans
			end
		end
	end
end

app/models/post_poem.rb
class PostPoem < ApplicationRecord

	belongs_to :song

	has_many :post_trans, inverse_of: :post_poem
	accepts_nested_attributes_for :post_trans, reject_if: :all_blank, allow_destroy: true
end

app/controllers/post_poems_controller.rb
class PostPoemsController < ApplicationController







    def show
        @song = Song.find(params[:id])
        @poem = PostPoem.find(params[:id])
        @tran = @poem.post_trans.new
        @trans = @poem.post_trans.all
    end

    def edit
    	@poem = PostPoem.find(params[:id])
    end

    def update
    	@poem = PostPoem.find(params[:id])
    	if @poem.update(post_poem_params)
            @song = @poem.song
    		redirect_to song_path(@song), notice: '歌詞内容が編集されました。'
    	else
    		render :index, notice: '歌詞内容の編集に失敗。'
    	end
    end

    def destroy
        @song = Song.find(params[:id])
        @poem = PostPoem.find(params[:id])
        tran = @poem.post_trans
        tran.user_id = tran.user.id
        # .find(params[:id])
        if tran.destroy
        redirect_to post_trans_path, notice: '翻訳は削除されました。'
        else
            @song = Song.find(params[:id])
            @poem = PostPoem.find(params[:id])
            @tran = @poem.post_trans.new
            render template: "post_poems/show", notice: '翻訳の削除に失敗。'
        end
    end

        private
    def song_params
        params.require(:song).permit(:artist_id, :song_name, :album_name, 
            post_poems_attributes: [:id, :poem, :song_id, :_destroy, 
                post_trans_attributes: [:id, :post_poem_id, :song_translate, :_destroy]])
    end

    def post_poem_params
        params.require(:post_poem).permit(:id, :poem, :song_id, :_destroy,
                post_trans_attributes: [:id, :post_poem_id, :song_translate, :_destroy])
    end

end

app/helpers/post_poems_helper.rb
module PostPoemsHelper
end

app/views/post_poems/edit.html.erb
<h1>編集</h1>
<%= form_for [@song, @poem], method: :edit do |f| %>
                    <% if @tran.errors.any? %>
                      <div id="error_explanation">
                        <h3><%= pluralize(@tran.errors.count, "error") %> invalidated your post.</h3>
                        <ul>
                        <% @tran.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group has-icon">
                        <h5>訳詩</h5>
                          <%= f.text_area :poem, size: "36" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.submit "翻訳登録", class: "btn btn-lg btn-primary btn-base-1 mt-20" %>
                      </div>
                    </div>
                <% end %>

app/views/post_poems/show.html.erb
               <%= @song.song_name %>


               <%= @poem.poem %>





                <%= form_for [@poem, @tran], method: :post do |f| %>
                    <% if @tran.errors.any? %>
                      <div id="error_explanation">
                        <h3><%= pluralize(@tran.errors.count, "error") %> invalidated your post.</h3>
                        <ul>
                        <% @tran.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group has-icon">
                        <h5>訳詩</h5>
                          <%= f.text_area :song_translate, size: "36" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <%= f.submit "翻訳登録", class: "btn-gradation" %>
                      </div>
                    </div>
                <% end %>


                <% @poem.post_trans.each do |tran| %>
                    <%= tran.song_translate %>

                    <% if tran.user_id == current_user.id  %>

                        <%= link_to "編集", edit_post_tran_path(tran) %>

                        <%= link_to "削除", post_poem_path(@poem),
                         method: :delete,
                         class: 'command',
                         data: { confirm: 'sure?'} %>

                    <% end %>

                <br>

                <% end %>